openapi: 3.0.0
servers: []
info:
  description: Provides News Feed for a user.
  version: 0.1.0
  title: FriendBook Feed Service
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags: []
paths:
  /feed:
    get:
      summary: Gets the News Feed for the given user & friends of the user.
      description: ''
      parameters:
        - name: userEmail
          in: query
          required: true
          schema:
            type: string
        - name: StartValue
          in: query
          required: false
          schema:
            type: string
            default: '1'
          allowEmptyValue: true
        - name: count
          in: query
          required: false
          schema:
            type: string
            default: '10'
          allowEmptyValue: true
      operationId: getFeed
      responses:
        default:
          description: Default response
          content:
            application/json:
              schema: {}
      requestBody:
        content:
          application/json:
            schema: {}
externalDocs:
  description: See AsyncAPI example
  url: 'https://mermade.github.io/shins/asyncapi.html'
components:
  schemas:
    Post:
      type: object
      name: post
      textMessage: String
      postResourceIdentifier: String
      postResourceType: String
      lastUpdated: String
  securitySchemes:
    api_key:
      type: apiKey
      name: api_key
      in: header
  links: {}
  callbacks: {}
security: []
